### ISSUE TITLE
Stuck on "Generating Puzzle..." RM2

### ISSUE THREAD

**Issue by ard0gg** [sandsmark/recrossable#15]
I'v installed recrossable via toltec (0.0.0-3) on my RM2. I have that latest 2.6.2.75 software with remarkable hacks installed. Additionally I do have the latest rm2fb client/server 1.0.1 installed as well. 

When I run recrossable from remux, I get the "generating puzzle..." screen and then it freezes. If I run recrossable from the command line using ```rm2fb-client recrossable``` I get the following:

``` bash
reMarkable: ~/ rm2fb-client recrossable
EPD platform plugin loaded!
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Framebuffer has wrong id: "mxcfb"
Framebuffer initialized: QImage(QSize(1404, 1872),format=QImage::Format_RGB16,depth=16,devicePixelRatio=1,bytesPerLine=2808,sizeInBytes=5256576) 5256576
Creating window
loaded word list in 3856 ms
Added 38123 words
Loading pattern "ginsberg"
128 open cells
0 1
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|25 |47 |34 |53 |XXX|11 |55 |36 |XXX|24 |8  |4  |41 |
| y | o | l | k |XXX| g | r | e |XXX| c | a | s | h |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|10 |   |   |   |XXX|18 |   |   |XXX|50 |   |   |   |
| a | s | e | a |XXX| l | i | b |XXX| u | n | t | o |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|13 |   |   |   |XXX|23 |   |   |XXX|19 |   |   |   |
| y | e | c | h |XXX| u | n | b |XXX| m | n | e | m |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|56 |   |   |   |54 |   |XXX|31 |27 |   |   |   |   |
| a | s | t | u | t | e |XXX| e | q | u | i | t | y |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|XXX|XXX|XXX|37 |   |   |XXX|39 |   |   |XXX|XXX|XXX|
|XXX|XXX|XXX| n | a | y |XXX| d | e | l |XXX|XXX|XXX|
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|17 |49 |44 |   |   |XXX|XXX|XXX|12 |   |6  |3  |2  |
| s | c | h | a | v |XXX|XXX|XXX| d | i | l | l | s |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|21 |   |   |XXX|XXX|XXX|XXX|XXX|XXX|XXX|15 |   |   |
| r | a | g |XXX|XXX|XXX|XXX|XXX|XXX|XXX| w | o | k |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|28 |   |   |26 |48 |XXX|XXX|XXX|33 |52 |   |   |   |
| i | n | t | r | o |XXX|XXX|XXX| p | e | p | p | y |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|XXX|XXX|XXX|9  |   |42 |XXX|14 |   |   |XXX|XXX|XXX|
|XXX|XXX|XXX| i | c | h |XXX| s | i | b |XXX|XXX|XXX|
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|7  |46 |51 |   |   |   |XXX|20 |   |   |5  |22 |1  |
| l | a | r | v | a | e |XXX| i | n | b | r | e | d |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|29 |   |   |   |XXX|16 |57 |   |XXX|30 |   |   |   |
| u | n | i | e |XXX| x | x | x |XXX| i | o | d | e |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|32 |   |   |   |XXX|35 |   |   |XXX|38 |   |   |   |
| r | e | p | r |XXX| e | x | t |XXX| n | s | e | c |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
|40 |   |   |   |XXX|43 |   |   |XXX|45 |   |   |   |
| e | t | a | s |XXX| r | i | e |XXX| g | e | n | l |
+---+---+---+---+---+---+---+---+---+---+---+---+---+
Across:
7. larvae
9. ich
10. asea
11. gre
12. dills
13. yech
14. sib
15. wok
16. xxx
17. schav
18. lib
19. mnem
20. inbred
21. rag
23. unb
24. cash
25. yolk
28. intro
29. unie
30. iode
31. equity
32. repr
33. peppy
35. ext
37. nay
38. nsec
39. del
40. etas
43. rie
45. genl
50. unto
56. astute

Down:
1. decl
2. sky
3. lop
4. stet
5. rose
6. lwp
7. lure
8. anni
11. gluey
14. sixte
17. sri
22. eden
24. cumuli
25. yaya
26. rivers
27. qed
33. pin
34. lect
36. ebbed
41. homy
42. hexer
44. hgt
46. anet
47. oses
48. oca
49. can
51. ripa
52. ebbing
53. kahuna
54. tav
55. rin
57. xxi
Generated crossword in 157 ms
virtual void EPRenderContext::renderNextFrame(QSGRenderer*, uint) can't render without a renderer
Segmentation fault
```

**Comment by haydensp** [comment]
I am also in the same boat. I'm assuming it's an issue regarding the update on the screen to solve the jagged line issue? IDK, I'll update again if I find a solution before @sandsmark.

That being said, this is the absolute coolest app I've used in a long time! Thank's for making it 🙏🏽

**Comment by ard0gg** [comment]
I've installed and configured the testing branch of toltec as implemented in [PR #310](https://github.com/toltec-dev/toltec/pull/310). This doesn't seem to fix the issue, but I'm also not sure if it's supposed to yet. Could very well be user error on my part. 

<details> 

``` bash
reMarkable: ~/ opkg print-architecture
arch all 100
arch armv7-3.2 160
arch rmall 200
arch rm2 250
```

``` bash
reMarkable: ~/ opkg list-installed
ca-certificates - 20210119-1
chessmarkable - 0.6.0-4
decay - 2.1.2-2
display - 1.0.1-2
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
erode - 2.1.2-2
fbdepth - 1.23.1-3
fbink - 1.23.1-3
findutils - 4.7.0-3
fret - 2.1.2-2
grep - 3.6-1a
harmony - 0.1.3-2
koreader - 2021.02-2
libatomic - 8.4.0-11
libc - 2.27-11
libcares - 1.17.1-1
libdlib - 19.21-1
libgcc - 8.4.0-11
libnghttp2 - 1.43.0-1
libopenssl - 1.1.1j-2
libpcre - 8.44-4
libpthread - 2.27-11
librt - 2.27-11
libssp - 8.4.0-11
libstdcpp - 8.4.0-11
libuv - 1.40.0-2
locales - 2.27-9
node - v14.15.5-2
opkg - 2020-12-24-9bbc7eae-1
recrossable - 0.0.0-6
remux - 0.1.9-2
rm2fb-client - 1.0.1-2
rot - 2.1.2-2
tarnish - 2.1.2-2
terminfo - 6.2-1
toltec-bootstrap - 0.0.2-2
wget - 1.20.3-4
xochitl - 0.0.0-4
zlib - 1.2.11-3
zoneinfo-asia - 2021a-1
zoneinfo-europe - 2021a-1
zshelf - 0.3.1-2
```
``` bash
reMarkable: ~/ cat /opt/etc/opkg.conf
src/gz entware https://bin.entware.net/armv7sf-k3.2
dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp
arch all 100
arch armv7-3.2 160
arch rmall 200
arch rm2 250
src/gz toltec-rmall https://toltec-dev.org/testing/rmall
src/gz toltec-rm2 https://toltec-dev.org/testing/rm2
```
</details>

**Comment by matteodelabre** [comment]
To clarify, that PR does not bring 2.6 support to Toltec (its main purpose was to solve toltec-dev/toltec#129). To track 2.6 support in Toltec, please see toltec-dev/toltec#322. Currently, we have [a working toolchain that can compile apps for 2.6](https://github.com/toltec-dev/toolchain#version-matrix), but packages compiled for 2.6 won’t work on older versions, which creates a distribution challenge for Toltec since not all users are on 2.6 yet.

**Comment by ard0gg** [comment]
Doh, of course. Thank you for the clarification. I was conflating RM1/RM2 with </>= 2.6 support.

**Comment by ard0gg** [comment]
I was able to figure out how to build apps with the Toltec 2.0.1 toolchain and can confirm that recrossable does appear to display properly (Yay!!).  I'm not sure if I should leave this issue open until 2.6 is fully supported through Toltec distribution.

**Comment by briankaemingk** [comment]
@ard0gg any chance you can share how you compiled with Toltec 2.0.1 toolchain? I've tried, but I'm getting some missing packages when I try to compile... Steps below:

* Cloned the Toltec Git repository.
* Switched to the testing branch.
* Edited the package/recrossable/package file, change image=qt:v1.4 to image=qt:v2.0.1.
* Attempt to make recrossable... looks like I'm missing some packages.. any help here is appreciated!:
```
(venv) bk@bk-VirtualBox:~/toltec$ make recrossable
./scripts/package_build.py  "recrossable"
[    INFO] toltec.builder: recrossable [rmall]: Fetching source files
[    INFO] toltec.builder: recrossable [rmall]: Building artifacts
[    INFO] toltec.builder: recrossable [rmall]: Only showing up to 50 lines of context. Use --verbose for the full output.
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libpango-1.0-0:amd64 (1.42.4-8~deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libcairo2:amd64 (1.16.0-4+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libmagickcore-6.q16-6:amd64 (8:6.9.10.23+dfsg-2.1+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libmagickwand-6.q16-6:amd64 (8:6.9.10.23+dfsg-2.1+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libcairo-gobject2:amd64 (1.16.0-4+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libpangoft2-1.0-0:amd64 (1.42.4-8~deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libgtk-3-common (3.24.5-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libpangocairo-1.0-0:amd64 (1.42.4-8~deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up gsettings-desktop-schemas (3.28.1-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up librsvg2-2:amd64 (2.44.10-2.1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up librsvg2-common:amd64 (2.44.10-2.1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up imagemagick-6.q16 (8:6.9.10.23+dfsg-2.1+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/compare-im6.q16 to provide /usr/bin/compare (compare) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/compare-im6.q16 to provide /usr/bin/compare-im6 (compare-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/animate-im6.q16 to provide /usr/bin/animate (animate) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/animate-im6.q16 to provide /usr/bin/animate-im6 (animate-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/convert-im6.q16 to provide /usr/bin/convert (convert) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/convert-im6.q16 to provide /usr/bin/convert-im6 (convert-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/composite-im6.q16 to provide /usr/bin/composite (composite) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/composite-im6.q16 to provide /usr/bin/composite-im6 (composite-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/conjure-im6.q16 to provide /usr/bin/conjure (conjure) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/conjure-im6.q16 to provide /usr/bin/conjure-im6 (conjure-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/import-im6.q16 to provide /usr/bin/import (import) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/import-im6.q16 to provide /usr/bin/import-im6 (import-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/identify-im6.q16 to provide /usr/bin/identify (identify) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/identify-im6.q16 to provide /usr/bin/identify-im6 (identify-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/stream-im6.q16 to provide /usr/bin/stream (stream) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/stream-im6.q16 to provide /usr/bin/stream-im6 (stream-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/display-im6.q16 to provide /usr/bin/display (display) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/display-im6.q16 to provide /usr/bin/display-im6 (display-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/montage-im6.q16 to provide /usr/bin/montage (montage) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/montage-im6.q16 to provide /usr/bin/montage-im6 (montage-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/mogrify-im6.q16 to provide /usr/bin/mogrify (mogrify) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/bin/mogrify-im6.q16 to provide /usr/bin/mogrify-im6 (mogrify-im6) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: Setting up adwaita-icon-theme (3.30.1-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: update-alternatives: using /usr/share/icons/Adwaita/cursor.theme to provide /usr/share/icons/default/index.theme (x-cursor-theme) in auto mode
[   ERROR] toltec.builder: recrossable [rmall]: Setting up imagemagick (8:6.9.10.23+dfsg-2.1+deb10u1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for mime-support (3.62) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for libglib2.0-0:amd64 (2.58.3-2+deb10u2) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for libc-bin (2.28-10) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for systemd (241-7~deb10u7) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up glib-networking:amd64 (2.58.0-2+deb10u2) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libsoup2.4-1:amd64 (2.64.2-2) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libsoup-gnome2.4-1:amd64 (2.64.2-2) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up librest-0.7-0:amd64 (0.8.1-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up libgtk-3-0:amd64 (3.24.5-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Setting up librsvg2-bin (2.44.10-2.1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
[   ERROR] toltec.builder: recrossable [rmall]: Processing triggers for libc-bin (2.28-10) ...
[   ERROR] toltec.builder: recrossable [rmall]: * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'libdlib'.
[   ERROR] toltec.builder: recrossable [rmall]: build() failed
Traceback (most recent call last):
  File "./scripts/package_build.py", line 64, in <module>
    if not builder.make(generic_recipe, arch_packages):
  File "/home/bk/toltec/scripts/toltec/builder.py", line 143, in make
    if not self._make_arch(
  File "/home/bk/toltec/scripts/toltec/builder.py", line 168, in _make_arch
    self._build(recipe, src_dir)
  File "/home/bk/toltec/scripts/toltec/builder.py", line 357, in _build
    self._print_logs(logs, "build()")
  File "/home/bk/toltec/scripts/toltec/builder.py", line 689, in _print_logs
    raise err
  File "/home/bk/toltec/scripts/toltec/builder.py", line 670, in _print_logs
    for line in logs:
  File "/home/bk/toltec/scripts/toltec/bash.py", line 416, in run_script_in_container
    raise ScriptError(f"Script exited with code {result['StatusCode']}")
toltec.bash.ScriptError: Script exited with code 255
make: *** [Makefile:60: recrossable] Error 1
```

**Comment by matteodelabre** [comment]
You need to run `make libdlib` first (and update the `image` field in `package/libdlib/package` as you did for the recrossable package). Our build system does not yet automatically trigger the build of missing dependencies. This is being tracked here: https://github.com/toltec-dev/toltec/issues/321. Sorry about that!

**Comment by briankaemingk** [comment]
All good, thanks, that worked for me!
